services:
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  prometheus:
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
    restart: unless-stopped

  next-server:
    build:
      context: ..
      dockerfile: benchmark/next-server/Dockerfile
    container_name: next-server
    ports:
      - "3000:3000"
    restart: unless-stopped